### PR TITLE
Add exception handeling for user addresses in vesting dashboard

### PR DESCRIPTION
**Pull request by ranatrk**
## Description
Add error handling for errors occurring when trying to add an invalid or non existent address in the vesting dashboard.
A small error is shown to the user, and the full log is printed in jsng shell for debugging if needed

## Fixes
**Invalid address:**
Screenshot from 2021-03-28 12-08-45

**Non existent address:**
Screenshot from 2021-03-28 12-09-01

## Related Issue
https://github.com/threefoldfoundation/tft-stellar/issues/332

### CODE REVIEW

**Comment by robvanmieghem** [comment]
This works but only for the vesting dashboard, the vesting service would still return a stellar sdk error for other clients like the mobile wallet which is also implementing a vesting possibility. Of course they would not send an invalid address but catching the stellar sdk exception at the point where it is raised seems like a cleaner solution to me.

**Comment by robvanmieghem** [comment]
get_balance is also a very  expensive call, it does a lot of external requests:
- at least 2 calls to horizon
- for every locked balance, a call to the unlock service to fetch the unlocktransaction

**Review by robvanmieghem — CHANGES_REQUESTED** [review]
Please see my comments

**Comment by ranatrk** [comment]
@robvanmieghem The service is updated by moving the error handling from the dashboard package to the service

**Pull request merged**
