### PR TITLE
Convert transactionfunding package to jsng package

### PR DESCRIPTION
**Pull request by ranatrk**
## Fix
Convert transaction funding package from jsx package to jsng package

## Related issue
https://github.com/threefoldfoundation/tft-stellar/issues/201

### CODE REVIEW

**Review by robvanmieghem — CHANGES_REQUESTED** [review]
@ranatrk Your last commit deleted all the files but added none

**Comment by ranatrk** [comment]
> @ranatrk Your last commit deleted all the files but added none

I apologize, the renamed folder for the package to be used (replacing - with a _) wasn't included in the commit. The last commit now included the renaming

**Review by robvanmieghem — APPROVED** [review]
Thank you @ranatrk.
Pleae don't submit the pycaches in the future

**Comment by ranatrk** [comment]
> Pleae don't submit the pycaches in the future

okay will make sure of that thank you

**Pull request merged**
